name 'rails_app_cookbook'
maintainer 'Joel Tanner Jones'
maintainer_email 'tannerjones10@gmail.com'
license 'all_rights'
description 'Installs/Configures rails_app_cookbook'
long_description 'Installs/Configures rails_app_cookbook'
version '0.1.0'

depends 'apt'
depends 'nginx'
depends 'postgresql'
depends 'database'
